### ISSUE TITLE
show thumbnail of bookmark

### ISSUE THREAD

**Issue by cadeyrn** [cadeyrn/keep-or-delete-bookmarks#11]
There was the proposal to show thumbnails of the bookmarks. I am not convinced about this one but let's record the proposal and decide at a later point.

**Comment by PanderMusubi** [comment]
How do you make this thumbnail if the same problem is there for https://github.com/cadeyrn/keep-or-delete-bookmarks/issues/1 ?

**Comment by cadeyrn** [comment]
Whatever it need to store and show thumbnails is a different kind of issue.

Websites can (and a lot of websites do this!) prevent being integrated via iframe. But capturing thumbnails and show these doesn't involve iFrames.

**Comment by PanderMusubi** [comment]
As an alternative, also this image can be used from the the page's HTML header:

    <meta property="og:image" content="http://blahblah.com/img/feature.png" />

**Comment by iwconfig** [comment]
Have you checked out https://www.thum.io/? You get 1000 screenshot hits per month for free and you could provide a way for users to add their own api key.

Here's an example screenshot: https://image.thum.io/get/maxAge/12/width/2000/https://github.com/cadeyrn/keep-or-delete-bookmarks/issues/11

I don't know what the maximum width/height available but it's more than good enough. Full page view is a paid feature though but I don't think it's needed.

Here's the documentation: https://www.thum.io/documentation/api/url.

You could also have a toggle button for showing a preview of the site.

1. It would save some of those free requests if you're a frequent "swiper" and/or have a lot of bookmarks
2. It would prevent sensitive, personal or whatever you don't want to be sent to thum.io, in regards to privacy
