### ISSUE TITLE
Japanese translation of "Keep or Delete Bookmarks version 1.0.1"

### ISSUE THREAD

**Issue by Shitennouji** [cadeyrn/keep-or-delete-bookmarks#18]
> keep-or-delete-bookmarks/src/_locales/日本語/messages.json
> locales: 日本語（ja-JP）

{
  "bookmarks_empty_state": {
    "message": "これでバッチリです！ もうブックマークを検査する必要はありません。"
  },
  "btn_delete_bookmark": {
    "message": "削除する"
  },
  "btn_keep_bookmark": {
    "message": "維持する"
  },
  "btn_open_bookmark": {
    "message": "開く"
  },
  "btn_open_whitelist": {
    "message": "ホワイトリストを開く"
  },
  "btn_skip_bookmark": {
    "message": "次へ"
  },
  "confirm_btn_cancel": {
    "message": "取り消す"
  },
  "confirm_btn_ok": {
    "message": "OK"
  },
  "confirm_checkbox": {
    "message": "確認のダイアログを有効にする"
  },
  "confirm_delete_bookmark": {
    "message": "ブックマークは、本当に削除して大丈夫でしょうか？"
  },
  "extension_description": {
    "message": "ブックマークの整理は面倒でうんざりです。Firefox のアドオン　Keep or Delete Bookmarks（ブックマークの削除や維持）を使用すれば、 \"Tinder\" や類似のサービスのようにブックマークを並べ替えることができ、この退屈な作業にいくらかの楽しさが得られます。"
  },
  "extension_name": {
    "message": "Keep or Delete Bookmarks（ブックマークの削除や維持）"
  },
  "btn_whitelist_remove_all": {
    "message": "ホワイトリストから全てを削除する"
  },
  "whitelist_delete_bookmark": {
    "message": "ブックマークを削除する"
  },
  "whitelist_empty_state": {
    "message": "ホワイトリストには、まだブックマークはありません。"
  },
  "whitelist_th_name": {
    "message": "名称"
  },
  "whitelist_th_path": {
    "message": "パス"
  },
  "whitelist_th_url": {
    "message": "URL"
  }
}

**Comment by cadeyrn** [comment]
Hi @Shitennouji,

thanks for your contribution and sorry for the very long delay. Finally I found some time to do a bit add-on development again and I developed a new version of Keep or Delete Bookmarks. There are not a lot of new strings but some new strings needs to be translated. Are you interested in updating your translation? Then I would include it once you provide it.

Thank you!

New strings:

  ```
"btn_previous_bookmark": {
    "message": "back"
  },
  "check_status_failure": {
    "message": "The bookmark may be broken."
  },
  "check_status_skipped": {
    "message": "No check possible."
  },
  "check_status_success": {
    "message": "The bookmark seems to be okay."
  },
  "date_added": {
    "message": "Date added"
  },
  "whitelist_remove_bookmark": {
    "message": "remove from whitelist"
  },
```

Notes:

- btn_previous_bookmark is a button to jump to the previous bookmark after you pressed the "skip" button. The string has to be as short as possible.
- date_added is a string that appears for the date when a bookmark was added to Firefox.

**Comment by Shitennouji** [comment]
### Hi @cadeyrn,

Yes, I am happy to help you with the translation.

New strings:
#
 "btn_previous_bookmark": {
  "message": "戻る"
},
"check_status_failure": {
  "message": "ブックマークが壊れている可能性があります。"
},
"check_status_skipped": {
  "message": "照合できません。"
},
"check_status_success": {
  "message": "ブックマークは大丈夫そうです。"
},
"date_added": {
  "message": "追加された日付"
},
"whitelist_remove_bookmark": {
  "message": "ホワイトリストから外す"
},

**Comment by cadeyrn** [comment]
Thank you very much! A new version is now online on addons.mozilla.org and it includes your translation. :)
