### ISSUE TITLE
Support key strokes

### ISSUE THREAD

**Issue by PanderMusubi** [cadeyrn/keep-or-delete-bookmarks#3]
Please support key strokes such as arrow left and right for delete and keep and space for next and enter for open, for example. If these keys are very hard to capture and might interfere with normal browser functionality, use Ctrl+ shortcuts.

**Comment by cadeyrn** [comment]
Great idea! I will investigate if it's possible to use these keys, otherwise I will find other shortcuts.

**Comment by cadeyrn** [comment]
@PanderMusubi I released Keep or Delete Bookmarks 2.0 and it includes your feature request:

- Left Arrow: show previous bookmark
- Right Arrow: show next (random) bookmark
- Enter: open bookmark
- Space: add bookmark to whitelist
- Backspace: delete bookmark (or opens confirmation dialog if enabled)
- in bookmark deletion confirmation dialog:
    - ESC: close dialog
    - Enter: delete bookmark

/cc @keunes, @toehold, @capturts (people who gave a thumbs up for the proposal)
