### ISSUE TITLE
Add link on folder name

### ISSUE THREAD

**Issue by PanderMusubi** [cadeyrn/keep-or-delete-bookmarks#5]
Please, add a link on the bookmark folder name that is displayed. Clicking on it should open the bookmark manager in that folder. If bookmark managers is not available, like on Firefox Mobile, try to open a page with all the bookmarks in that bookmark folder.

**Comment by keunes** [comment]
A +1 to the OP from my side. I have many bookmarks of which a large chunk is outdated and can be deleted. But some I'd want to preserver, just differently structured. A link to the folder would help me reorganise my stuff by providing a quick path to the place where I can make these edits.

**Comment by cadeyrn** [comment]
There is no API to interact with the Firefox bookmark manager. But it should be possible to restrict the bookmarks to a specific folder.

What should happen if this folder has sub folders? Should these be included or not?

Related: #6.

**Comment by PanderMusubi** [comment]
Not even opening the bookmark manager such as via Ctrl+Shift+O can be triggered? Can another bookmark add-on be triggered to open?

Perhaps a dynamic page could be generated showing all bookmarks for that folder. Bit if this is too much troubles, better close it.

**Comment by cadeyrn** [comment]
> Not even opening the bookmark manager such as via Ctrl+Shift+O can be triggered? Can another bookmark add-on be triggered to open?

No. But even it would be possible you still couldn't tell the bookmarks manager that a specific folder should be opened or a specific bookmark should be selected.

If you want interact that an add-on interact with another add-on **both** add-ons have to implement some logic to communicate.

> Perhaps a dynamic page could be generated showing all bookmarks for that folder. Bit if this is too much troubles, better close it.

Yes, that's possible and I will keep this ticket open for this one.

**Comment by keunes** [comment]
> Perhaps a dynamic page could be generated showing all bookmarks for that folder.

For me that wouldn't do it. If opening a specific folder isn't possible, my current workaround (search using Bookmark Search Plus 2) suffices.

> If you want interact that an add-on interact with another add-on both add-ons have to implement some logic to communicate.

That'd be cool (interaction with the above-mentioned BSP2, for example)

**Comment by cadeyrn** [comment]
I'll close this issue because it's still not possible for a WebExtension to open a specific folder in the library. For working only for a subset of bookmarks we still have #6.
